### ISSUE TITLE
Test updated python3 version of markdown-pp and update repo

### ISSUE THREAD

**Issue by joncamfield** [OpenInternet/Documentation-Builder#9]
potential reason behind the *ModuleNotFoundError: No module named 'Processor'* errors are python version mismatches.  Current markdown-pp is tagged to an old release (at least following the current build instructions and scripts).  We need to test if the newer markdown-pp version works with python 3.7.1 and the rest of the build process

**Comment by joncamfield** [comment]
To use python3:

sudo apt install python3-setuptools pip
sudo pip install MarkdownPP

change the builddoc script's make_markdown function to the following:

```
make_markdown() {
    cd "$BUILD_DIRECTORY"/target
    markdown-pp -o "$BUILD_DIRECTORY"/"$DOC_MARKDOWN" "$BUILD_DIRECTORY"/target/"$INDEX_FILE" 
    cd "$RUN_DIR"
}
```

(noting that setting up a python virtual environment to avoid the sudo pip install path would a better practice)

**Comment by dhersch1** [comment]
After following instructions above, the PDF was built, but with some errors.  Error output saved in attached file output.txt, which is a capture of the Terminal output after running builddoc with updated MarkdownPP and Python3.  Built PDF is also attached (guide.pdf)

[guide.pdf](https://github.com/OpenInternet/Documentation-Builder/files/3257508/guide.pdf)
[output.txt](https://github.com/OpenInternet/Documentation-Builder/files/3257509/output.txt)

**Comment by dhersch1** [comment]
Below are some comparisons between the PDFs generated in Ubuntu 16.04 (w/ Python2 and OpenInternet/markdown-pp) (on the left) and Ubuntu 19.04 (w/ Python3 and source markdown-pp) (on the right).  

The first issue I noticed between the PDFs was that the bookmarks were different.  On the left, the next bookmark after "USER DEVICE ASSESSMENT" is "VULNERABILITY...", whereas on the left "VULNERABILITY..." is missing and has been replaced by two bookmarks that seem to be unprocessed markdown.

The next differences I noticed were between the pages near those bookmarks.  On the left, the Linux section from pages 107-108 looks the same as the right, except for a few discrepancies in the indentation and the page number, which is 101 on the right.  But when it reaches the Recommendations subsection, the entirety of that section on the right looks to be unprocessed markdown on the right.

This unprocessed markdown continues for a long time.  It includes the entirety of the blue section on the left, and into the next header sections (without the blue background).  The PDFs sync back up on page 137 on the left and page 122 on the right, under the "Setting up your environment" subheader.

This likely accounts for the discrepancies in page numbers, and is likely occurring elsewhere throughout the document, as these errors did not start on the same page number. 

When these errors started, the documents were 6 pages apart.  After the errors stop, they were 15 pages apart.  Overall, the error document is only 22 pages behind the original. Hopefully, there are only a few other sections causing errors.

![image](https://user-images.githubusercontent.com/35816411/58969979-8a780680-8786-11e9-8422-ff8f4ca7295f.png)

**Comment by dhersch1** [comment]
Per the most recent commit  (https://github.com/SAFETAG/SAFETAG/commit/86296157cf2983fbd2f2e53361e4c4a289a63b4e), the PDF is being built successfully in Ubuntu 19.04 (w/ Python3 and the source markdown-pp).

There is a discrepancy between the 16.04/Python2 and the 19.04/Python3 PDFs, in that the former has 248 pages and the latter has 233 pages, but upon cursory inspection this seems only to be the result of small differences in font sizing and paragraph spacing.  Otherwise, the content of both PDFs seems to be the same.

Calling builddoc in the Ubuntu 19.04 Terminal still results in a number of error messages being output, but there are less in this most recent trial than in the earlier one.  An output text file is attached with the Terminal output from calling builddoc using the Safetag instructions, as well as the built PDFs for both 16.04 and 19.04.

[guide_v3_Ubuntu16.04.pdf](https://github.com/OpenInternet/Documentation-Builder/files/3258505/guide_v3_Ubuntu16.04.pdf)
[guide_v3_Ubuntu19.04.pdf](https://github.com/OpenInternet/Documentation-Builder/files/3258506/guide_v3_Ubuntu19.04.pdf)
[output_v3_Ubuntu19.04.txt](https://github.com/OpenInternet/Documentation-Builder/files/3258507/output_v3_Ubuntu19.04.txt)

**Comment by joncamfield** [comment]
To confirm that the docs are the same, you can run builddoc with -d for debug.  It will output a reference to the temporary directory where it compiles the markdown and html precursors to the PDF.  those two files should be identical (can be diff 'ed) to the ones created via Python 2.

The warnings are referring to defined footnotes or references which (I think) are "named" in the reference listings but are not being linked to in the document any more.  Worth (using the temp file's markdown copy) spot-checking a few of the line numbers and confirming that.
